### ISSUE TITLE
Navigation bar won't display the correct Menu

### ISSUE THREAD

**Issue by kathyduarte** [ucsc/ucsc-gutenberg-blocks#10]
When I make change to the Menu I've selected as my primary navigation, they won't show up unless I reselect it from the dashboard -> Appearance -> Editor 
<img width="1147" alt="Screen Shot 2022-04-19 at 9 23 44 AM" src="https://user-images.githubusercontent.com/62771705/164050623-38438694-fc1c-4977-bf18-d18482292edd.png">

**Comment by superkumario64** [comment]
@kathyduarte this repo is for Campus Directory, Class Schedule and Course Catalog. I'm going to close this issue.
