### ISSUE TITLE
Requesting more width on the tile layout

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-gutenberg-blocks#100]
Hi Kumar --

Becca (rsalley@ucsc.edu) has made the following request in NC1347815:

Is it possible to eventually change the width of the tile layout of the campus directory block if it is just one profile being represented in the column?  Why:  So the text for the office will not break into two lines: 

See an example of what is happening here:
https://engineering.wordpress.ucsc.edu/departments/applied-mathematics/people/

The mobile view shows the table having more width.

Kindest Regards, Becca

**Comment by superkumario64** [comment]
Hey Bryn, 

It would be a bit of work to add a checkbox on tiled to do something like width 100% like it does in mobile but on full browser view. Or I'm not exactly sure how/if we want to preserve the old regular styles.

The mobile fix doesn't address the issue of the office line breaking into two lines for everyone. For example Pascale Garaud's office is still two lines on a mobile view.

<img width="496" alt="Screen Shot 2022-10-04 at 10 08 03 AM" src="https://user-images.githubusercontent.com/1696357/193882731-64cee9ee-1429-4ea3-bf8d-e0e9cb016c55.png">

@teresasilva71 thoughts on this issue?

**Comment by kanarb** [comment]
Maybe we should add this request to the agenda for our 10/6 web team meeting?

**Comment by teresasilva71** [comment]
I don't think we need to update this. Looks like she is displaying 2 people at a time. A better directory layout option for her would be the list layout.
Bryn, maybe you could suggest she change the layout type and see if that better suits her needs?

**Comment by superkumario64** [comment]
@teresasilva71 if this is label "wontfix" and the same issues are described in #102 I'm going to close this issue down.
