### ISSUE TITLE
Email is not showing up when using Directory Block

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-gutenberg-blocks#104]
Angie in INC1356624 reports that:

"Campus Email" and "Other Email" are no longer options as per ticket #INC1328282.

Example: https://engineering.wordpress.ucsc.edu/people/faculty/

**Comment by superkumario64** [comment]
Hi Bryn,

When I edit that page I see that neither the option for "Campus Email" nor "Other Email"  are selected. If there select one of those and republish it should display the email.

Best,
Kumar

**Comment by kanarb** [comment]
Thanks Kumar. I've added that info to INC1356624.

**Comment by kanarb** [comment]
Hi Kumar. Angie is not seeing the "Campus Email" or "Other Email" options. Perhaps it's a permissions issue? Here's the screenshot she provided:
<img width="328" alt="Screen Shot 2022-10-13 at 9 27 17 AM" src="https://user-images.githubusercontent.com/5742093/195653337-80c0a55f-93ce-444a-a409-37d1daefd332.png">

**Comment by kanarb** [comment]
I shared your suggestion through the ticket, but haven't heard back yet.
