### ISSUE TITLE
Directory Block Accessibility Errors

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-gutenberg-blocks#106]
Hi Kumar. Becca (in INC1385561) is reporting an accessibility issue with campus campus directory blocks:

I am running the Wave check tool on the pages within engineering.wordpress.ucsc.edu 
Any page that utilizes the campus directory tile block comes up with "Empty Link" error.
For example: 
This page:
https://engineering.wordpress.ucsc.edu/people/faculty/
Has
149 Errors
149 X Empty link

**Comment by kanarb** [comment]
![Screen Shot 2022-11-07 at 12 03 40 PM](https://user-images.githubusercontent.com/5742093/200441914-e56dbb16-c870-465a-ade4-3e2a4d11d6a7.png)

**Comment by superkumario64** [comment]
@kanarb a fix for this was pushed out and now https://engineering.wordpress.ucsc.edu/people/faculty/ has 0 errors.
