### ISSUE TITLE
Directory Page: The full title on vacant positions is not showing in WordPress, but is showing in Cascade.

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-gutenberg-blocks#111]
![Picture1](https://user-images.githubusercontent.com/7795841/203156252-7302ded8-fc23-4761-b667-ad5c373c21ab.png)

![Picture2](https://user-images.githubusercontent.com/7795841/203156258-025dfc50-bc7c-4d93-9121-e201f6b1e818.png)

**Comment by kanarb** [comment]
We looked at this in our team meeting on 12/15/2022 and identified that it was a bug related to commas.

**Comment by superkumario64** [comment]
@kanarb I have a release to address this going to dev for testing: https://github.com/ucsc/ucsc-gutenberg-blocks/pull/114/files

We could test and release this week to prod, however I understand if we want to hold off until after curtailment.

**Comment by superkumario64** [comment]
@kanarb here is a page showing the Vacant positions working on dev: https://test-kagarwal.wordpress-dev.ucsc.edu/2022/12/19/vacancies/

We can respond to Campus Press when we are ready to go to prod with this fix.

**Comment by kanarb** [comment]
@superkumario64 the test looks good. Go ahead and push to prod.

**Comment by superkumario64** [comment]
@kanarb this issue seems to be resolved on production: https://officeofresearch.wordpress.ucsc.edu/ord/contact-us/
