### ISSUE TITLE
Client says selecting CITL in the block crashes the page

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-gutenberg-blocks#117]
> We noticed that when we select CITL in the campus directory widget on the beta site, it crashes the system.

<img width="350" alt="thumbnail" src="https://user-images.githubusercontent.com/36719/228682500-cb38689c-fb30-4c23-89f5-a1c0d53c2b5b.png">

**Comment by superkumario64** [comment]
@knice I have a release prepared to address this issue: https://github.com/ucsc/ucsc-gutenberg-blocks/compare/v1.1.9...v1.1.10#diff-083ea705c06468693062ca2aa9462eed2c26cbe75b96eac5182b789b0b6c6fb0R276

The Ldap uses parenthesis to group arguments in it's query, so the (CITL) in their department name was breaking the query. Using ldap_escape allows the query to work properly.
