### ISSUE TITLE
Previewing a page with Campus Directory block set to Lecturers only (for faculty) shows incorrect results

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#13]
On the Campus Directory set up I selected Lecturer only for the Faculty Types. When I preview the page with the Campus Directory block, some staff are listed in addition to Lecturers. For example, Stephanie Hinkle is the Department Manager, she is not a lecturer. Stephanie Sawyer is listed. She is staff. The same thing happens with other selections from Faculty Types. I don't think Staff should be included. 

Same types of issue when I select other checkboxes (e.g. Graduate Students only) lists faculty in addition to Graduate Students. It does not seem like the checkbox filters are working for Faculty Types or for Staff Types or for Graduate Students.

![Campus Directory Preview Lecturer selected](https://user-images.githubusercontent.com/9750983/165881735-80629ce8-d23f-40fc-a580-b5c8fe5a7e77.png)
![Campus Directory Set Up Lecturer selected](https://user-images.githubusercontent.com/9750983/165881740-9e976f9c-309c-45e9-81d2-c3b58f9e4699.png)

**Comment by CorinneOC** [comment]
For reference: 
https://test-corinne.wordpress.ucsc.edu/?page_id=45&preview=true

**Comment by superkumario64** [comment]
@CorinneOC Can you test this in the current WCMS? I have a feeling this may be the behavior in the current WCMS.

**Comment by CorinneOC** [comment]
For example: https://envs.ucsc.edu/faculty/directory_lecturers.php

**Comment by superkumario64** [comment]
wordpress: https://superkumario64.com/2022/03/16/just-campus-dir/
wcms: https://history-dev.ucsc.edu/faculty/profiles/lecturer.php
