### ISSUE TITLE
Course Catalog and Class Schedule no longer pulling in Department or Subject info

### ISSUE THREAD

**Issue by Herm71** [ucsc/ucsc-gutenberg-blocks#133]
Yesterday, Monday January 29, I noticed that  neither the Class Schedule nor the Course Catalog blocks are pulling in the Department or Subject info when adding either block. I can confirm that these blocks worked properly on Thursday, January 25, when @superkumario64 and I had a meeting to discuss this block.

This behavior can be repeated by testing on a CampusPress test site.

**Screenshot**

![cat-sched](https://github.com/ucsc/ucsc-gutenberg-blocks/assets/1000543/007b3e7d-df2e-41f3-9173-e83e52b3918c)

**Comment by superkumario64** [comment]
@Herm71 are the permalinks set to plain? Sometimes the REST API calls fail when set to plain, every other setting works.

**Comment by Herm71** [comment]
@superkumario64 the Permalinks on my [Sandbox CampusPress Site](https://test-jchafin.wordpress.ucsc.edu/sample-page/) were set to **Date and Time**. I know sometimes they need to be saved to "set" them properly, so I changed back to **Plain**, saved, then changed back to simply **Post name** and tested it out. Same behavior.

**Comment by superkumario64** [comment]
@Herm71 The API requests are timing out like what happens when we try to load dev sometimes (
https://test-kagarwal.wordpress.ucsc.edu/wp-json/ucscgutenbergblocks/v1/departmentcode):

<h1>
            Error 504 <a href="#">Gateway timeout</a>
        </h1>
        <p>
            Sorry, something went wrong at our end. <br>
            This page will refresh in 5 seconds, which should be enough time for the issue to be fixed. Please refer to
		<a href="https://status.campuspress.com/" target="_blank">CampusPress status</a>
            if you continue to see this
		message.
	
        </p>

I'll email Campus Press.

**Comment by superkumario64** [comment]
API calls stopped timing out.
