### ISSUE TITLE
Some functionality for Campus Directory block does not include functionality in WCMS Directory Pages

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#15]
I am noticing a number of 'features' that are available in the WCMS Directory pages that are absent from the Campus Directory block.

Examples are:
- For the Page Layout: the ability to create sections and subsections. 
https://wcmshelp.ucsc.edu/page-types/directory-page/sections-and-sub-sections.html

Example page in WCMS with sections and sub-sections:
https://urelations.ucsc.edu/about/staff/index.php

**Comment by superkumario64** [comment]
@CorinneOC the user can create multiple Campus Directory blocks and combine them with other Gutenberg blocks to achieve this functionality. Closing this.
