### ISSUE TITLE
Training/docs: Page with Campus Directory block - Introductory Paragraph: does it have WYSIWYG functionality

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#16]
When I opt to have an introductory paragraph in a page with a Campus Directory block, I am not seeing that the block is WYSIWYG. Does it have that ability? The introductory paragraph in the WCMS has that functionality.
![Campus Directory intro paragraph](https://user-images.githubusercontent.com/9750983/165883924-d5df447a-d3f7-4bb9-bb37-115b38924e6e.png)

**Comment by superkumario64** [comment]
Use Gutenberg blocks. The user can use Gutenberg blocks on the page before adding a Campus Directory box. Closing this.
