### ISSUE TITLE
Campus Directory block Tiled Layout only shows 3 tile columns

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#17]
When I preview a Tiled Layout it 
only shows 3 tile columns. This is different from the Tiled Layout in WCMS that shows 4 columns.

![Campus Directory Tiled Layout sample](https://user-images.githubusercontent.com/9750983/165996239-748cf3af-ddf6-44ee-90c9-51fb17cdf982.png)

![WCMS Tiled Layout](https://user-images.githubusercontent.com/9750983/165996370-0d899964-9947-40f8-8a3c-cdae5e6eff46.png)

**Comment by teresasilva71** [comment]
If I remember correctly, the number of columns depends on the screen size and should be responsive? There may be a maximum width tho. @superkumario64 might want to check with Rob on max width of theme.

**Comment by CorinneOC** [comment]
For reference: 
https://test-corinne.wordpress.ucsc.edu/?page_id=47&preview=true

**Comment by CorinneOC** [comment]
This is resolved.
