### ISSUE TITLE
Campus Directory block images have gold border

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#18]
The images for the directory pages have a gold border. Is that as desired? Ask Teresa and Adam.

**Comment by superkumario64** [comment]
@CorinneOC can you include links to the pages you create?

**Comment by CorinneOC** [comment]
For reference: https://test-corinne.wordpress.ucsc.edu/?page_id=43&preview=true

**Comment by superkumario64** [comment]
@CorinneOC those borders are from WordPress warnings that show up when Previewing. It looks fine when publishing: https://test-corinne.wordpress.ucsc.edu/corinne-test-directory-page-list-faculty/

Closing this issue.
