### ISSUE TITLE
Campus Directory - individual profile page (styling question)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#21]
When you click on the name of someone listed in the Directory page it loads the individual profile page (if that is enabled). The styling of the individual profile page is much different (very small) than in WCMS. The text for the websites is reduced to one word (e.g. Personal Site, says Personal).

Also there is text that says "Just another UCSC WordPress Multisite Network site"
![Campus Directory individual profile page example](https://user-images.githubusercontent.com/9750983/166001194-49f12714-ee5a-431d-adff-5d28673dcd37.png)

Comparison page in WCMS:
https://history.ucsc.edu/about/faculty.php?uid=danthony
![WCMS individual profile page example](https://user-images.githubusercontent.com/9750983/166000872-2ff7ea39-997a-46ac-836a-ead13028d6c3.png)

**Comment by Herm71** [comment]
@superkumario64 Check out this post. You're looking for `echo do_blocks()`
https://fullsiteediting.com/lessons/how-to-use-php-templates-in-block-themes/
clone/fork the theme and add it to your local dev. you can get the template parts from there. I'd be happy to have a sesh with you to walk you through it.

**Comment by superkumario64** [comment]
@Herm71 I added `echo do_blocks()` and I am getting a PHP error. I added a meeting for Monday for us to catch up, you are free to create a PR if you think that can resolve the issue before then.

**Comment by superkumario64** [comment]
Header and footer are correct now. closing.
