### ISSUE TITLE
Campus Directory - Create Custom List (no text guidance)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#22]
On the Campus Directory block if you choose the option Create My Own List of People to Display, there is no guidance of what to type in and in what format. 

As compared with WCMS it says
"List Individuals (Enter CruzIDs separated by commas)"
"List individuals in the order you wish them to appear in the page"

![WCMS Directory Create a List text w instructions](https://user-images.githubusercontent.com/9750983/166003697-820a5931-ebda-4746-8f1e-3dd3acd2f33e.png)

WCMS Help page (for creating a custom list)
https://wcmshelp.ucsc.edu/page-types/directory-page/custom-list.html

I tested creating a list of CruzIDs without comma separating them and no people appeared in the Preview.

**Comment by CorinneOC** [comment]
For reference;
https://test-corinne.wordpress.ucsc.edu/wp-admin/post.php?post=4&action=edit

**Comment by superkumario64** [comment]
fixed via: https://github.com/ucsc/ucsc-gutenberg-blocks/pull/36/files

**Comment by CorinneOC** [comment]
Can the text size for text guidance be a smaller font?

**Comment by CorinneOC** [comment]
This is resolved.
