### ISSUE TITLE
Campus Directory - Create Custom List alphabetizes individuals (individuals not listed in order they are typed)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#23]
In a Campus Directory block, if you create a custom list of individuals and then preview, the individuals are listed in alphabetical order by last name (not in the order they are typed into the area).

Example:

I typed in sshinkle, corinne, henryh

The preview shows:
Henry Heikkinen
Stephanie Hinkle
Corinne O'Connell

This is different from the order I typed the CruzIDs.

![Campus Directory custom list](https://user-images.githubusercontent.com/9750983/166009699-36bcfd72-6d0b-43ea-b789-f927c8c8cecb.png)

![Campus Directory custom list preview order different](https://user-images.githubusercontent.com/9750983/166009706-c6934c7f-fa02-4090-835c-29731cdac7c3.png)

**Comment by superkumario64** [comment]
@CorinneOC this is the current behavior on the WCMS Campus Directory so I am closing this issue.

**Comment by CorinneOC** [comment]
I respectfully don't agree.
https://wcmshelp.ucsc.edu/page-types/directory-page/custom-list.html

In WCMS ustom Lists will enable you display people in the order you enter them.

**Comment by CorinneOC** [comment]
For reference:
https://test-corinne.wordpress.ucsc.edu/wp-admin/post.php?post=4&action=edit

**Comment by CorinneOC** [comment]
This is resolved.
