### ISSUE TITLE
Unable to add new or change navigation menu items

### ISSUE THREAD

**Issue by Yingkit22** [ucsc/ucsc-gutenberg-blocks#25]
<img width="510" alt="Screen Shot 2022-04-29 at 12 10 48 PM" src="https://user-images.githubusercontent.com/103080126/166022152-3a5be12e-c919-415b-b6be-c12467489a86.png">
<img width="1166" alt="Screen Shot 2022-04-29 at 12 11 51 PM" src="https://user-images.githubusercontent.com/103080126/166022350-3f9bacf6-32f1-4788-8fd7-fd96e4be31b3.png">

**Comment by superkumario64** [comment]
@Yingkit22  this repo is for Campus Directory, Class Schedule and Course Catalog. I'm going to close this issue.
