### ISSUE TITLE
Class Schedule block - term text cut off for word Quarter (when previewing)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#27]
I created a page with a Class Schedule block, the term 2022 Summer Quarter is cut off (the rightmost r of Quarter) does not appear.

![Class Schedule term text cut off](https://user-images.githubusercontent.com/9750983/166058729-cd6bc91c-f5e9-4a40-9a1e-52403b8bcdc1.png)

It is fine for 2022 Fall Quarter and for 2022 Winter Quarter and for 2022 Spring Quarter

I would seem that the Search box could be a bit smaller to accommodate the space needed to display 2022 Summer Quarter.

**Comment by superkumario64** [comment]
@CorinneOC I don't see that error on my end. It could browser window size/zoom magnification level you are at. Do you have a link to the page you created for this?

**Comment by CorinneOC** [comment]
For reference: https://test-corinne.wordpress.ucsc.edu/?page_id=38&preview=true&d=HIS

**Comment by CorinneOC** [comment]
This is resolved.
