### ISSUE TITLE
Course Catalog page - headers do not appear above columns

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#28]
When viewing a Course Catalog page, the headers do not appear above the columns.

![Course Catalog page headers](https://user-images.githubusercontent.com/9750983/166060011-cfc351c1-dec7-4139-a058-7f1b0f081caf.png)

**Comment by superkumario64** [comment]
@CorinneOC the headers are all where they should be on my end. Do you have a link to the page you created to test this?

**Comment by CorinneOC** [comment]
For reference: 
https://test-corinne.wordpress.ucsc.edu/?page_id=40&preview=true

**Comment by superkumario64** [comment]
I *think* this is again a preview warning issue that can be ignored: https://test-corinne.wordpress.ucsc.edu/corinnes-test-course-catalog-page/

**Comment by superkumario64** [comment]
preview issue closing
