### ISSUE TITLE
Course Catalog page - instructions have borders

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#29]
When viewing a Course Catalog page, the instruction text has green borders.

![Course Catalog instructions w borders issue](https://user-images.githubusercontent.com/9750983/166060185-17af20da-5f1b-4fa9-befc-1fdc15e5dd54.png)

**Comment by superkumario64** [comment]
I don't see those borders on my end, can you link me to the page where you tested this?

**Comment by CorinneOC** [comment]
For refernce: https://test-corinne.wordpress.ucsc.edu/?page_id=40&preview=true

**Comment by superkumario64** [comment]
Preview warnings, looks fine: https://test-corinne.wordpress.ucsc.edu/corinnes-test-course-catalog-page/

closing.
