### ISSUE TITLE
Course Catalog - Search box position

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#30]
When viewing a Course Catalog page the Search box is positioned very close to the text "Search Dept Courses".

It would be better if the Search box could be positioned a bit more to the right.

![Course Catalog Search box position](https://user-images.githubusercontent.com/9750983/166061455-a99481be-b080-442f-93b6-14aa587a3f6e.png)

**Comment by superkumario64** [comment]
fixed via: https://github.com/ucsc/ucsc-gutenberg-blocks/pull/35

**Comment by CorinneOC** [comment]
This is resolved.
