### ISSUE TITLE
Campus Directory - Individual names or other data has yellow lines

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#39]
I'm not sure if this is how I am looking at a published page, but when viewing a List formatted directory page the individual's name has yellow underlines, also anything else that has a link (e.g. email address, personal site, etc.) has a yellow line. This is different than WCMS.
![Campus Directory text with yellow links](https://user-images.githubusercontent.com/9750983/168336592-bf816717-d9b3-413c-b264-10564cd7e4a4.png)

**Comment by superkumario64** [comment]
It looks like wcms only adds the underline on hover.

**Comment by CorinneOC** [comment]
It looks like the email addresses and websites still have hyperlink yellow underscore. They should just be hover as well if it is to look like WCMS.

**Comment by superkumario64** [comment]
underlines have been removed. closing.
