### ISSUE TITLE
WordPress error when plugin is enabled

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-gutenberg-blocks#5]
I have this plugin set to install when I start my local WP dev environment. When I go to WordPress, I get this error (PHP white screen).

> Notice: wp_register_script was called incorrectly. Scripts and styles should not be registered or enqueued until the wp_enqueue_scripts, admin_enqueue_scripts, or login_enqueue_scripts hooks. This notice was triggered by the ucscblocks handle. Please see Debugging in WordPress for more information. (This message was added in version 3.3.0.) in /var/www/html/wp-includes/functions.php on line 5663 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5663) in /var/www/html/wp-login.php on line 400 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5663) in /var/www/html/wp-login.php on line 416 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:5663) in /var/www/html/wp-includes/functions.php on line 6712

**Comment by knice** [comment]
I'm using [@wordpress/env](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-env/) for local dev. Here is my config file for my dev environment:

````json
{
  "mappings": {
    "wp-content/plugins": "./plugins",
    "wp-content/mu-plugins": "./mu-plugins",
    "wp-content/themes": "./themes"
  },
  "themes": [ "WordPress/theme-experiments" ],
  "plugins": [
    "https://github.com/WordPress/gutenberg/releases/download/v12.1.0/gutenberg.zip",
    "https://downloads.wordpress.org/plugin/http-headers.zip",
    "https://github.com/ucsc/ucsc-gutenberg-blocks/archive/refs/heads/main.zip"
  ]
}
````

**Comment by superkumario64** [comment]
@knice these 2 commits should address this issue:

- https://github.com/ucsc/ucsc-gutenberg-blocks/commit/ce33c608dbce4b47f81bd2febc3272daa620b632
- https://github.com/ucsc/ucsc-gutenberg-blocks/commit/2ee94c03e7eb78d811148a0cbbabd15f0011d2d3

Most of the blocks will work except for the Campus Directory. Nether @wordpress/env or https://localwp.com/ have the ldap package installed for PHP and I wasn't able to find a way to configure them to install ldap. I created a Docker wordpress environment with LDAP installed and the Campus Directory ldap calls were still failing but this time it couldn't authenticate with the Active Directory server. After much debugging I added a local cert and nginx proxy to redirect to HTTPS and I can now run the Campus Directory in this local docker environment. 

In the next sprint Tai and I will do some testing on the local docker environment and document it so others can use it as well.

**Comment by knice** [comment]
Thank you for working on this @superkumario64! I didn't think about the additional library and the need for auth credentials. I understand that makes it difficult to use this plugin for local testing. 

Do you think it is possible for the plugin to fail gracefully if the LDAP library and required credentials aren't configured? 

I'm envisioning a scenario where we have additional blocks in the plugin that don't require API calls or campus server integrations to work properly. 

Maybe other types of blocks should be in another plugin altogether? I'm open to your thoughts on how to manage that.

**Comment by superkumario64** [comment]
@knice It works like that currently. Tai and I weren't able to get the docker environment up and running on his machine, so he is just Local and not working on the Campus Directory. That being said, it could be a bit more graceful.  I will look into something where editors can only use the block if the settings for that block are all set.
