### ISSUE TITLE
Campus Directory  - Change text for Page Layout to Layout Types

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#50]
When you add a Campus Directory Block, above the radio buttons for the layout types it says Page Layout.

![wp_campus_directory_block_layout_type](https://user-images.githubusercontent.com/9750983/175758265-eda85a19-e521-402f-ac69-080f060ad93b.jpg)

Since multiple Campus Directory Blocks can be added to a page, the text should say Layout Type instead.

Corinne

**Comment by superkumario64** [comment]
completed closing.
