### ISSUE TITLE
Question: Campus Directory - Does WordPress have an accordion feature?

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#52]
Supposing you wanted to have a page with links to different directories. 
For example:

Faculty
Lecturers
Grad Students

Do you know if the page could expand a collapse just a People type (e.g. expand Lecturers Campus Directory block)

**Comment by superkumario64** [comment]
@CorinneOC the Campus Directory can be nested within the WordPress-Gutenbergs' default Accordion block. Attached are some screen shots:

All closed:
<img width="1374" alt="Screen Shot 2022-06-28 at 9 22 27 AM" src="https://user-images.githubusercontent.com/1696357/176231024-5a231bf2-3da4-4b87-a974-24db05d0cc4c.png">

First Open:

<img width="1346" alt="Screen Shot 2022-06-28 at 9 22 49 AM" src="https://user-images.githubusercontent.com/1696357/176231051-07da6b15-57db-4f26-b773-47e3ab87b742.png">


Does this work?

**Comment by superkumario64** [comment]
there is now an accordion block that works for everyone except Corinne. closing for now.
