### ISSUE TITLE
Remove Intro Paragraph functionality from Campus Directory Block

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#54]
Per Teresa,

Please remove the Intro Paragraph functionality from the Campus Directory Block. It does not offer the needed functionality and individuals can simply create a textblock above their Campus Directory Block instead.

The current Intro Paragraph text block doesn't have WYSIWYG.

**Comment by superkumario64** [comment]
completed. closing
