### ISSUE TITLE
Departments Listed (from Campus Directory block)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#60]
I'm looking at the department names from the Campus Directory block. Some have Department of [dept name] as in Department of Environmental Studies. Others don't start with the name Department. We should check in with Paul on the API.

**Comment by CorinneOC** [comment]
For Campus Directory the departments need to come from the actual Campus Directory don't they? Not AIS. I'm confused about what the reasoning is for departments and subjects. I am guessing that subjects would entail custom lists? Subjects are not in Campus Directory to my knowledge.

**Comment by CorinneOC** [comment]
If you look at the Campus Directory and do an Advanced Search and click on Department/College/Unit that is how the departments should be listed I believe (for the Campus Directory block). I could be entirely wrong but it makes sense to me.

**Comment by superkumario64** [comment]
Happy with static list. closing.
