### ISSUE TITLE
Unable to view block regardless of login status 

### ISSUE THREAD

**Issue by knice** [ucsc/ucsc-gutenberg-blocks#67]
On this page: https://test-kagarwal.wordpress-dev.ucsc.edu/

I don't see the block, whether I'm logged in or not. I believe it might be caused by role permissions. Before I contact CampusPress, can we confirm that the block is visible for a logged out user in a local test environment? I want to eliminate the possibility of an issue in the plugin permissions before contacting CP.

### Logged in
![screenshot-2022-07-28-123234](https://user-images.githubusercontent.com/36719/181622258-31350c3e-2950-4d67-9c05-c165c398fcfd.jpg)

### Logged out
![screenshot-2022-07-28-123316](https://user-images.githubusercontent.com/36719/181622360-3674ef2f-477e-4f58-ae41-2b27823c75e3.jpg)

**Comment by superkumario64** [comment]
@knice this accordion block is going to be an interesting one to debug. On my devbox I have UCSC 2022 theme enabled and the accordion block works. I do see this error:
```
Block validation: Block validation failed for `core/cover` ({name: 'core/cover', icon: {…}, keywords: Array(0), attributes: {…}, providesContext: {…}, …}apiVersion: 2attributes: {url: {…}, id: {…}, alt: {…}, hasParallax: {…}, isRepeated: {…}, …}category: "media"deprecated: (7) [{…}, {…}, {…}, {…}, {…}, {…}, {…}]description: "Add an image or video with a text overlay — great for headers."edit: r=> {…}example: {attributes: {…}, innerBlocks: Array(1)}getEditWrapperProps: n=>{let o={};return t&&(o=t(n)),ct(o,e,n,ot)}icon: {src: {…}}keywords: []name: "core/cover"providesContext: {}save: ƒ (e)styles: []supports: {anchor: true, align: true, html: false, spacing: {…}, color: {…}}title: "Cover"transforms: {from: Array(3), to: Array(2)}usesContext: []variations: [][[Prototype]]: Object).

Content generated by `save` function:

<div class="wp-block-cover alignfull is-light has-custom-content-position is-position-bottom-center" style="padding-top:0px;padding-bottom:80px;min-height:625px"><span aria-hidden="true" class="has-white-background-color has-background-dim-0 wp-block-cover__gradient-background has-background-dim"></span><img class="wp-block-cover__image-background" alt="A redwood forest." src="https://unsplash.com/photos/ylJtKpTYjn4/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MXx8cmVkd29vZCUyMGZvcmVzdHxlbnwwfHx8fDE2NTI2Mzg2MTM&amp;w=1920" style="object-position:19% 82%" data-object-fit="cover" data-object-position="19% 82%"/><div class="wp-block-cover__inner-container"></div></div>

Content retrieved from post body:

<div class="wp-block-cover alignfull is-light has-custom-content-position is-position-bottom-center" style="padding-top:0px;padding-bottom:80px;min-height:625px"><span aria-hidden="true" class="wp-block-cover__background has-white-background-color has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background" alt="A redwood forest." src="https://unsplash.com/photos/ylJtKpTYjn4/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MXx8cmVkd29vZCUyMGZvcmVzdHxlbnwwfHx8fDE2NTI2Mzg2MTM&amp;w=1920" style="object-position:19% 82%" data-object-fit="cover" data-object-position="19% 82%"/><div class="wp-block-cover__inner-container"></div></div>
```

In  Campus Press Dev, the accordion block works when CampusPress Flex theme enabled. However when you enable the UCSC 2022 theme the block crashes and shows this error in console: 
```
TypeError: Cannot read properties of undefined (reading 'InspectorControls')
    at edit (index.js?ver=6.0:1:18066)
    at ft (react-dom.min.js?ver=6.0:1:43451)
    at ts (react-dom.min.js?ver=6.0:1:111300)
    at Fr (react-dom.min.js?ver=6.0:1:77758)
    at Dr (react-dom.min.js?ver=6.0:1:77686)
    at Rr (react-dom.min.js?ver=6.0:1:77549)
    at Nr (react-dom.min.js?ver=6.0:1:74544)
    at react-dom.min.js?ver=6.0:1:30170
    at unstable_runWithPriority (react.min.js?ver=6.0:1:7430)
    at xn (react-dom.min.js?ver=6.0:1:29947)
```

**Comment by Herm71** [comment]
This issue was tested on my `wordpress-dev` site and [it works as it should](https://test-jchafin.wordpress-dev.ucsc.edu/aug-4-kumar/). 

A comparison between @superkumario64 's test site and mine did not reveal significant differences. Same plugins installed, same theme.

I suggested starting with a fresh site in the `dev` environment.

**Comment by knice** [comment]
2022-08-05: I just verified that this issue appears to be resolved on wordpress-dev. A basic accordion block containing static content works as expected. On the prod network, the summary element is empty, but I assume that is because prod has no yet received the update from dev. @superkumario64, is that the case?

**Comment by superkumario64** [comment]
@knice correct dev has a newer release. Mine and Corrines sites still don't run the accordion block with ucsc-2022 theme enabled on dev. I emailed Campus Press and they will have a look. But yes for most all other sites on dev it seems to be resolved.

**Comment by knice** [comment]
@superkumario64 I have verified on (this sample page on the dev network)[https://test-raknight.wordpress-dev.ucsc.edu/sample-accordion/] and [your sample page](https://test-kagarwal.wordpress-dev.ucsc.edu/) that the accordion block works as expected in both the UCSC 2022 theme and the WordPress core theme Twenty Twenty-Two. 

I don't think this is a CampusPress issue. Is there another page we should look at to see the error you are seeing? And do you still have the issue in a different browser?

**Comment by superkumario64** [comment]
@knice it seems to be working on my site now. But Corinne, who has been testing the blocks, I went on her site and it is still broken: https://test-corinne.wordpress-dev.ucsc.edu/wp-admin/post.php?post=49&action=edit

**Comment by superkumario64** [comment]
As per rob this is fixed. closing.
