### ISSUE TITLE
Campus Directory: Consider suppressing the Department/Division selection options when Creating own list

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#68]
When one wants to create a custom list (rather than using the automatic feed) for the Campus Directory I think the options to select the Department or Division should be hidden entirely. If one were to toggle back to the Use Automatic Feed option then the Set Department or Division option (in the People and Information to Display area) should display.

See attachment.[](url)
![Campus Directory Block Custom List](https://user-images.githubusercontent.com/9750983/182294715-bc6dca5b-6e52-4c7d-8d42-b5a86c851934.jpg)

**Comment by superkumario64** [comment]
fixed. closing
