### ISSUE TITLE
Please remove Post type from Course Catalog and Class schedule blocks

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-gutenberg-blocks#70]
![course catalog block](https://user-images.githubusercontent.com/7795841/183712639-22395c07-e93a-464e-a7a7-5bab887bbcb4.jpg)
This content type should be a Page, not a post.
We don't want date and author on this type of block...it's static content.

**Comment by superkumario64** [comment]
@teresasilva71 the date and author are not added by these blocks.

**Comment by superkumario64** [comment]
@teresasilva71 I'm going to close this, reopen it if you need to.
