### ISSUE TITLE
Campus Directory block - email address feed

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#77]
There seems to be a difference between WCMS and WordPress Campus Directory functionality in that if an individual has multiple email addresses listed in their Campus Directory profile it is listing both of them (Campus email and Other email fields in Campus Directory profile).

See Sandy Schmidt (both email addresses are the same).
![Campus Directory email field](https://user-images.githubusercontent.com/9750983/186021503-7fc0ed21-2641-45f2-929a-6448fde41e4d.jpg)
![Dev Campus Directory block 2 email addresses](https://user-images.githubusercontent.com/9750983/186021806-0df73efa-833c-4421-9c8e-123881b2108d.jpg)

**Comment by CorinneOC** [comment]
I think it is just coincidence that her profile has the same email addresses but that being said the WCMS only lists 1 email address.

**Comment by CorinneOC** [comment]
See example for Stephanie Sawyer. She has 2 different email addresses in her Campus Directory profile.
![Dev Campus Directory block 2 dif email addresses](https://user-images.githubusercontent.com/9750983/186022328-7ed86cf5-8410-452c-810c-6fa81ab99bdf.jpg)

**Comment by CorinneOC** [comment]
I think Kumar may have mentioned that University Relations' WCMS Directory page has some customization that might suppress an Other Email Address if it is identical to the Campus Email Address.

**Comment by superkumario64** [comment]
@CorinneOC I'm going to close this and then we can open a new issue if Teresa decides she wants to change how emails work.
