### ISSUE TITLE
Add functionality to Expand All/Collapse All Accordion Blocks on a page

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#79]
Please add the functionality to Expand All/Collapse All Accordion Blocks on a page. Sample functionality in WCMS is on the Global Engagement page [https://global.ucsc.edu/about/org-chart-directory.php](url)

**Comment by superkumario64** [comment]
@CorinneOC this ability is in production with the Accordion Wrapper block.

**Comment by CorinneOC** [comment]
I verified this in production. I may need to do more testing though.
