### ISSUE TITLE
Campus Directory - List Layout Information to Display

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#80]
In the Campus Directory block there are options to indicate the "List Layout Information to Display". When you have selected the Tiled Layout should it say Tiled Layout Information to Display? I'm not sure how that appears in WCMS.
![Campus Directory List Layout Info To Display](https://user-images.githubusercontent.com/9750983/187526302-b229f4d9-d5f7-475d-89ae-c16f524dca09.jpg)

**Comment by superkumario64** [comment]
@CorinneOC this change is out on Production. We tested it on dev earlier, so I'm going to close it down.
