### ISSUE TITLE
On Accordion block, enlarge width of Accordion Item Title

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#82]
On an Accordion block, the width of the text area to specify an Accordion Item Title is too narrow to fully display some Accordion Item Title names. Request to widen the size of the Accordion Item Title area. See example:

![Accordion Item Title width too narrow](https://user-images.githubusercontent.com/9750983/187955745-a8b15122-1a67-4b70-bdba-5d20cf98117a.jpg)

It looks like the width is current 22 characters however you can certainly type more than 22 characters but the excess won't display when you are editing the Accordion Item Title. When you view the page though it does display the full text.

Global Engagement has Accordion Item Titles that exceed 22 characters (e.g. International Scholar Services).

Note: this is an issue both when the Accordion block is collapsed and expanded.

**Comment by CorinneOC** [comment]
I have verified this is fixed in DEV.

**Comment by superkumario64** [comment]
@CorinneOC The fix is now live on production. Warning production caches the JS files that fix this heavily, you may need to do a hard browser refresh `CMD + Shift + R' and then you will be able to see the new accordion title box.

**Comment by CorinneOC** [comment]
I have verified this fix in production.
