### ISSUE TITLE
On vacant position listing, slug thumbnail is still appearing even when "Image" is unchecked

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-gutenberg-blocks#83]
Jennie from Office of Research reported that when she adds a vacant position, the thumbnail still appears, even when she selects it NOT to appear.
https://officeofresearch.wordpress.ucsc.edu/ord/

**Comment by superkumario64** [comment]
@teresasilva71 It looks like all thumbnails are showing on that page. With the photo option unselected, I would assume no thumbnails show be visible. Correct?

**Comment by teresasilva71** [comment]
Right. When someone UN-checks the image option, no images should appear.

**Comment by superkumario64** [comment]
@teresasilva71 @CorinneOC The fix is now live on production.

**Comment by superkumario64** [comment]
Closing this issue.
