### ISSUE TITLE
Directory Block- thumbnails still appearing even when checkbox is unchecked

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-gutenberg-blocks#84]
Jennie from OR reported that the thumbnails are still showing even though she didn't select the images to appear
https://officeofresearch.wordpress.ucsc.edu/ord/
![photo unchecked](https://user-images.githubusercontent.com/7795841/189179236-0eeeb0c7-4482-4634-8436-bf1cc61fbffa.jpg)

**Comment by CorinneOC** [comment]
Sorry I must have missed that in my recent testing. Kumar let me know when it's ready to test.

**Comment by superkumario64** [comment]
@CorinneOC no big deal. If you have some time, can you test out the rest of the checkboxes on the Information to Display checkbox group?

**Comment by CorinneOC** [comment]
In DEV have verified that when the Photo checkbox is not checked the thumbnail does not appear (correct behavior).

**Comment by superkumario64** [comment]
Great, I have asked Campus Press to deploy the release to production. They will let us know when it on production.

**Comment by superkumario64** [comment]
@teresasilva71 @CorinneOC The fix is now live on production.

**Comment by superkumario64** [comment]
closing this issue.
