### ISSUE TITLE
WordPress accordion jumping to top of page when clicking Expand All

### ISSUE THREAD

**Issue by kanarb** [ucsc/ucsc-gutenberg-blocks#88]
Becca Alley (rsalley) in INC1319925 reports:

On https://engineering.wordpress.ucsc.edu/research/

WordPress accordion jumps to the "top of page" when clicking expand all instead of staying where the according is placed on the page. 

How do I make it stay in the place where expand all was selected?

Note: The according is in the according wrapper, following instructions found in database KB0019546

**Comment by superkumario64** [comment]
@kanarb this issue has been resolved.

**Comment by kanarb** [comment]
Becca tested and reports that it works as intended.
