### ISSUE TITLE
Course Catalog: With > 1 Course Catalog, Expand All/Collapse All Doesn't Work

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#89]
When you have more than one Course Catalog block on a page, the Expand All/Collapse all only functions on the first Course Catalog block. The links to Expand All and Collapse All do not work on the other Course Catalog blocks on the page. 

Also the Sorting only works on the first Course Catalog block.

**Comment by teresasilva71** [comment]
I thought we couldn't have more than one catalog or schedule block per page ?

**Comment by superkumario64** [comment]
@teresasilva71 There is a technical limitation of how the underlying laravel/vue app works that limits us on one schedule block per a page. For the course catalog its a bug with the html and javascript that prevents us from having two catalog blocks on one page. If we use html classes vs ids and if javascript would walk the DOM relative to where the block is, we could render two course catalogs on one page.

**Comment by superkumario64** [comment]
@CorinneOC this issue is fixed in production.

**Comment by CorinneOC** [comment]
I also tested in production. This looks resolved.
