### ISSUE TITLE
Weird "Content" box on directory page

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-gutenberg-blocks#94]
Jennie K. from Office of Research is asking about why the "content" box is appearing and how to get rid of it.
https://officeofresearch.wordpress.ucsc.edu/ord/contact-us/
![contents box](https://user-images.githubusercontent.com/7795841/191617560-5c65b74d-ad9c-415f-8a70-34286f8a4ab1.jpg)
I can't tell if this is a block issue, an accordion issue or a menuing issue.

**Comment by superkumario64** [comment]
@teresasilva71 I reached out to campus press and it appears to be coming from this plugin here: https://officeofresearch.wordpress.ucsc.edu/wp-admin/options-general.php?page=toc

**Comment by teresasilva71** [comment]
Thanks! She must have turned that on at some point.
