### ISSUE TITLE
Campus Directory Block: Table layout with Campus Email checked lists Email Campus Email (on published page)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#96]
In the Campus Directory block setup when you have Campus Email checked on a Table Layout, when you publish the page the column says Email Campus Email.

![Table Layout Email Campus Email](https://user-images.githubusercontent.com/9750983/192387583-2587fa0a-a79b-4ff1-9c9a-2da429d934b4.jpg)

**Comment by superkumario64** [comment]
@CorinneOC @teresasilva71 this fix is in production.
