### ISSUE TITLE
Campus Directory Block: Table layout with Other Email checked lists Email Other Email (on published page)

### ISSUE THREAD

**Issue by CorinneOC** [ucsc/ucsc-gutenberg-blocks#97]
In the Campus Directory block setup when you have Other Email checked on a Table Layout, when you publish the page the column says Email Other Email.

![Table Layout Email Other Email](https://user-images.githubusercontent.com/9750983/192387705-b062e937-97bb-4e21-b664-3f027a9b0f74.jpg)

**Comment by superkumario64** [comment]
@CorinneOC @teresasilva71 this fix is in production.
