### ISSUE TITLE
Tiled View - expand display beyond 4? 

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/ucsc-gutenberg-blocks#98]
I'm not sure if there is a neat way to do this but if you look at this page: https://engineering.wordpress.ucsc.edu/people/faculty/ you can see that the tiled layout of a max of 4 looks odd.
Is there a way for us to have it default to the width of the inserted block?

**Comment by teresasilva71** [comment]
Hi Kumar, we have our first ticket re: this issue. :) INC1341903 Bumping this priority to medium. LMK if/when you'll get a chance to investigate this.

**Comment by kanarb** [comment]
The ITR for this is: INC1341903

**Comment by teresasilva71** [comment]
Hi Kumar, if Becca already has a block in use, does she need to remove the block and then add it again?

**Comment by kanarb** [comment]
@superkumario64  Becca is reporting (INC1341903) that she isn't seeing this change yet. Is it awaiting CampusPress approval?

**Comment by superkumario64** [comment]
@teresasilva71 @kanarb CampusPress just approved the changes on Dev. I checked them out, it looked good and I asked them to promote the release to production. My guess is it will be on production later today or tomorrow.

**Comment by superkumario64** [comment]
@teresasilva71 @kanarb this release is out in production. The page that was referenced in this issue now has two empty columns preventing it from expanding past 4 columns. 

![Screen Shot 2022-10-04 at 10 11 55 AM](https://user-images.githubusercontent.com/1696357/193883327-c8a85254-0629-4809-9c08-42620efcbd3a.png)

If they remove those columns, more than 4 columns with appear in that campus directory block.
